services:
    fw.wallet:
        class: Forjaweb\EthbridgeBundle\Controller\WalletController
        calls:
            - [setContainer, ["@service_container"]]
    fw.eth:
        class: Forjaweb\EthbridgeBundle\Controller\ServiceController
        calls:
            - [setContainer, ["@service_container"]]
    fw.erc20:
        class: Forjaweb\EthbridgeBundle\Controller\ERC20Controller
        calls:
            - [setContainer, ["@service_container"]]
